{% set version = "2.1.0" %}

package:
  name: pykakasi
  version: {{ version }}

source:
  url: https://github.com/miurahr/pykakasi/archive/v{{ version }}.tar.gz
  sha256: 2ab64adb903adb912307fd838ed55c67a0f6977f2116679375bbf5dac5c45c59

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - klepto
    - wheel
  host:
    - python
    - pip
    - deprecated
    - importlib-metadata  # [py<38]
  run:
    - python
    - deprecated
    # unfortunately, this really run-depends on setuptools, see
    # https://github.com/miurahr/pykakasi/blob/v2.1.0/src/pykakasi/properties.py#L8
    - setuptools

test:
  # will run run_test.py
  requires:
    - pytest
  imports:
    - pykakasi
  source_files:
    - tests/

about:
  home: https://github.com/miurahr/pykakasi
  license: GPL-3.0-only
  license_file: COPYING
  summary: Convert Japanese Kana-kanji sentences into Kana-Roman in simple algorithm.

  description: |
    `pykakasi` is a Python Natural Language Processing (NLP) library to transliterate _hiragana_,
    _katakana_ and _kanji_ (Japanese text) into _romaji_ (Latin/Roman alphabet). It can handle characters in NFC form.

    It is based on the kakasi library, which is written in C.

  doc_url: https://pykakasi.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/miurahr/pykakasi

extra:
  recipe-maintainers:
    - h-vetinari
